apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mbop
  name: mbop
  namespace: boot
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: mbop
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mbop
    spec:
      containers:
      - env:
        - name: KEYCLOAK_SERVER
          value: http://192.168.x.x:12345
        image: 127.0.0.1:5000/mbop:1
        imagePullPolicy: IfNotPresent
        name: mbop
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
